### ISSUE TITLE
tidak bisa menuju index.php

### ISSUE THREAD

**Issue by cyber12drago** [2018-PemrogramanWeb-B/tugas7-fp-team_rocket#1]
Saya mencoba untuk melakukan register tetapi belum saat melakukan success register tidak dapat mengarah ke halaman index.php. 

![aa](https://user-images.githubusercontent.com/36811855/50200416-67000180-0388-11e9-840a-29fb964dd527.jpg)

**Comment by rigold** [comment]
memang harus login dulu, jadi setelah register, lalu login

**Comment by cyber12drago** [comment]
iya saya sudah register tp gk ngarah ke login dan saat coba login setelah register. invalid username or password.

![aaa](https://user-images.githubusercontent.com/36811855/50204589-fbbe2b80-0397-11e9-8cae-75d7afe33155.jpg)

**Comment by bosmobosmo** [comment]
coba cek di database ada entry di tabel user apa tidak

**Comment by cyber12drago** [comment]
ok sudah bisa. thanks
